version: '3.8'

services:
  user_app:
    build:
      context: ./user_service
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db:5432/booking_info
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=1234
    depends_on:
      - db

  thing_app:
    build:
      context: ./thing_service
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db:5432/booking_info
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=1234
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: booking_info
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local
